<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Enightx.Pos.Wpf</RootNamespace>
    <AssemblyName>Enightx.Pos.Wpf</AssemblyName>
    <Version>1.0.19</Version>
    <AssemblyVersion>1.0.19.0</AssemblyVersion>
    <FileVersion>1.0.19.0</FileVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ApplyUpdate.ps1" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="release-public-key.pem" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <ProjectReference Include="..\Enightx.Pos\Enightx.Pos.csproj" />
  </ItemGroup>

</Project>
