<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Enightx.Pos.Wpf</RootNamespace>
    <AssemblyName>Enightx.Pos.Wpf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enightx.Pos\Enightx.Pos.csproj" />
  </ItemGroup>

</Project>
